spring.application.name=async-communication-service
bus.service.url=http://localhost:8082/buses
student.service.url=http://localhost:8081/students
gps.service.url=http://localhost:8002/locations
notification.service.url=http://localhost:8001/notifications
route.service.url=http://localhost:8080/routes
groupement.service.url=http://localhost:8000/groupement
auth.service.url=http://localhost:8087/auth