server:
  port: 3009
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/async_db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    compatibility-verifier:
      enabled: false
logging:
  level:
    root: INFO
    org.springframework: DEBUG

# URLs des autres microservices (adapter si tu as un gateway ou discovery)
services:
  student:
    url: http://localhost:8082/api/students
  bus:
    url: http://localhost:8081/api/buses
  gps:
    url: http://localhost:8002/locations
  notification:
    url: http://localhost:8001/notifications
  route:
    url: http://localhost:8080/routes
  group:
    url: http://localhost:8000/groups
  auth:
    url: http://localhost:8087/auth/validate
  gateway:
    url: http://localhost:8088/api

# Resilience4j (exemples)
resilience4j:
  circuitbreaker:
    instances:
      communicationService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      communicationService:
        maxAttempts: 3
        waitDuration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: "*"
