spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/async_db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    compatibility-verifier:
      enabled: false
logging:
  level:
    root: INFO
    org.springframework: DEBUG


# Resilience4j (exemples)
resilience4j:
  circuitbreaker:
    instances:
      communicationService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      communicationService:
        maxAttempts: 3
        waitDuration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: "*"
