server:
  port: 3009
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/async_db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    compatibility-verifier:
      enabled: false
logging:
  level:
    root: INFO
    org.springframework: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/